CREATE TABLE BOOK(
  id   int   GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  ISN VARCHAR(128),
  AUTHOR VARCHAR(128),
  OWNER VARCHAR(128),
  TITLE VARCHAR(128)
);

CREATE TABLE USER(
  id   int   GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  NAME VARCHAR(128),
  PASSWORD VARCHAR(128)
);

insert into BOOK (ISN,AUTHOR,OWNER,TITLE) VALUES ('137-364','David Baldacci',null,'Freddy and the French Fries');
insert into BOOK (ISN,AUTHOR,OWNER,TITLE) VALUES ('835-275','Judith Krantz',null,'Scruples Two');
insert into BOOK (ISN,AUTHOR,OWNER,TITLE) VALUES ('923-265','Cao Xueqin','us','Dream of the Red Chamber');
insert into BOOK (ISN,AUTHOR,OWNER,TITLE) VALUES ('023-465','Denise Robins','admin','Love s Broken Idol');
insert into BOOK (ISN,AUTHOR,OWNER,TITLE) VALUES ('473-945','Anne Rice','admin','Blood and Gold');
insert into BOOK (ISN,AUTHOR,OWNER,TITLE) VALUES ('934-576','Rex Stout', null,'The Second Confession');
insert into BOOK (ISN,AUTHOR,OWNER,TITLE) VALUES ('945-721','Eleanor Hibbert', null,'Daughter of Anna');
*
insert into USER (NAME, PASSWORD) VALUES ('us','12345');
insert into USER (NAME, PASSWORD) VALUES ('ad','qwerty');